### ISSUE TITLE
App raises an error when I try to run it

### ISSUE THREAD

**Issue by SSJDeathSpawn** [Shaam-K/pomodoro-timer#1]
When I try to run it using
`python3 ./manage.py runserver`
It returns the following:

```
Traceback (most recent call last):
  File "path/pomodoro-timer/./manage.py", line 22, in <module>
    main()
  File "path/pomodoro-timer/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/core/management/base.py", line 427, in run_from_argv
    connections.close_all()
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/db/utils.py", line 212, in close_all
    for alias in self:
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "path/pomodoro-timer/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tailwind_project.settings'
```
I already installed all the requirements in the venv that I ran this from 
There's also no help in the readme on what I am supposed to do

**Comment by Shaam-K** [comment]
I didnt commit settings.py, I just realized thanks

**Comment by Shaam-K** [comment]
Before starting this, make sure you create a new MySQL database for this project.

In settings.py you need the following

Fill in the following details that are in caps 

django secret key: line 22 
you can generate one by creating an empty django project and copy pasting that secret key to this project or just type in something if you just want to test it out.

Settings.py line 22

`
SECRET_KEY = "SECRET KEY HERE"`

MySQL Database: Settings.py line 80-89

1) Name of database
2) Host  (_example : 130.0.0.5_)
3) Port  (_example: 4405_)
4) User  (_default is root_)
5) Password for MySQL

Settings.py line 80-89
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "DATABASE NAME",
        'HOST': "HOST",
        'PORT': "PORT",
        'USER': "USER, DEFAULT IS ROOT",
        'PASSWORD': "PASSWORD",
    }
}

```
Sorry for not making this process user-friendly :/ and thanks for pointing that out my bad.
